### ISSUE TITLE
Should match sass files only

### ISSUE THREAD

**Issue by thearnica** [Progyan1997/storybook-addon-sass-postcss#3]
Hey! Thank you for this addon - it really saved by day.
There is only one problem - it handles not only `sass` files, but `css` as well

https://github.com/Progyan1997/storybook-addon-sass-postcss/blob/main/src/index.ts#L74

As a result this addon conflicts with storybook default settings leading to `style-loader` being applied twice.

```
(1:1) /src/common/styles/css-reset.css Unknown word

> 1 | import api from "!../../../node_modules/@storybook/builder-webpack5/node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    | ^
  2 |             import content from "!!../../../node_modules/@storybook/builder-webpack5/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[8].use[1]!./css-reset.css";
```

🙏 it is possible to aim only files which should be processed?

**Comment by Progyan1997** [comment]
@thearnica You can pass your custom regex in 2nd parameter (option).
```diff
module.exports = {
  addons: [
-   'storybook-addon-sass-postcss',
+   {
+     name: 'storybook-addon-sass-postcss',
+     options: {
+       rule: {
+         test: /\.(scss|sass)$/i,
+       },
+     },
+   },
  ]
}
```
